### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ggomma** [devJaem/recruit-hub#1]
# feedback

## 총평

- README.md를 잘 작성하였습니다.
- API 명세서를 구체적으로 잘 작성하였습니다.
- ERD를 잘 작성하였습니다.
- 매우 잘 작성한 코드입니다.
- 코드 가독성이 좋고 구현 역량이 훌륭합니다.

## 구현 사항

- 필수
  - [x] API 명세서 작성
  - [x] ERD 작성
  - [x] 회원가입 API
  - [x] 로그인 API
  - [x] Access Token 인증 Middleware
  - [x] 내 정보 조회 API
  - [x] 내 이력서 생성 API
  - [x] 내 이력서 목록 조회 API
  - [x] 내 이력서 상세 조회 API
  - [x] 내 이력서 수정 API
  - [x] 내 이력서 삭제 API
- 선택
  - [x] 역할 인가 Middleware
  - [x] 채용담당자가 모든 이력서 조회 API
  - [x] 채용담당자가 특정 이력서 조회 API
  - [x] 채용담당자가 이력서 상태 변경 API
  - [x] 채용담당자가 이력서 로그 목록 조회 API
  - [x] RefreshToken 인증 Middleware
  - [x] 토큰 재발급 API (🔐 RefreshToken 인증 필요)
  - [x] 로그아웃 API (🔐 RefreshToken 인증 필요)

### 변수명 1
아래 코드에서 `index` 보다는 `router`나 다른 이름을 사용하는 것이 읽기에 좋습니다.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/app.js#L5

### 변수명 2
`userRoles` 보다 단수인 `userRole`이 낫습니다.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/middlewares/require-roles.middleware.js#L5

### 기본값
아래 코드에서 만약 환경변수가 존재하지 않을 경우에 대한 기본값을 넣어주면 더욱 좋습니다.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/constants/env.constant.js#L4-L11

### 리턴 값의 분리
아래 코드에서 `error`와 `payload`를 분리하는 것이 좋습니다. 예를들어 `{ payload: ..., error: ... }` 와 같은 식이요.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/utils/jwt.util.js#L4-L15

### 자주 사용하는 값은 상수로
아래 코드에서 `expired`를 `EXPIRED_ERROR` 등으로 관리하는 것이 잠재적으로 발생할 수 있는 오타 이슈를 줄여줄 수 있습니다.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/middlewares/require-access-token.middleware.js#L28

### refresh token 관리
하나의 userId는 하나의 refresh token만 가질 수 있게 설계하는 것이 더 직관적이지 않을까요?

### transaction 사용
transaction을 사용하기 위해서는 `tr` 객체를 이용해야 합니다.

https://github.com/devJaem/recruit-hub/blob/6fb07a5f84c5d001185fba49b1ecfe49b70f0113/src/routers/resume.router.js#L24-L45

**Comment by devJaem** [comment]
적용 완료하였습니다. 감사합니다.
